name: Deploy Frontend to Host Nginx

on:
  push:
    branches: [ "master" ]
    paths:
      - 'frontend_vue/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './frontend_vue/package-lock.json'

      - name: Install Dependencies
        run: npm ci
        working-directory: ./frontend_vue

      - name: Build Project
        run: npm run build
        working-directory: ./frontend_vue

      - name: Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend_vue/dist/*"
          target: "/var/www/html/"
          strip_components: 2

      - name: Fix Permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo 
            sudo chmod -R 755 /var/www/html
            echo "âœ… Done!"