name: Deploy Backend to Hetzner

on:
  push:
    branches: [ "master" ]
    paths:
      - 'BackendSpring/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./BackendSpring

      - name: Copy JAR to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # <-- УБРАЛ ЛИШНЕЕ ТИРЕ
          source: "BackendSpring/target/*.jar"
          target: "/root/Java-jar-files/"
          strip_components: 2

      - name: Restart Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Java-jar-files/
            
            echo 
            rm -f app.jar
            
            echo 
            mv BackendSpring*.jar app.jar
            
            echo 
            docker rm -f $(docker ps -a -q --filter name=backend) || true
            docker rm -f java-backend || true
            
            echo 
            docker-compose up -d --build backend
            
            echo 
            docker restart prometheus || true
            

            
