name: Deploy Tg-bot to Hertzner
on:
  push:
    branches: ["master"]
    paths:
      - 'tg-service/**'
      - '.github/workflows/deploy-tg-bot.yml'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: ./tg-service
        run: |
          mvn clean package -DskipTests
          mv target/*.jar target/app2.jar

      - name: Copy JAR to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "tg-service/target/app2.jar"
          target: "/root/Java-jar-files/"
          strip_components: 2

      - name: Restart Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Java-jar-files/
            echo "Restarting TG Bot..."
            
            # 1. Принудительно останавливаем и удаляем старый контейнер
            # || true нужно, чтобы скрипт не падал, если контейнера еще нет
            docker stop java-bot || true
            docker rm -f java-bot || true
            
            # 2. Запускаем сборку с нуля
            docker-compose up -d --build tg-bot